name: Generate Snake

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: zagham-nadeem
          svg_out_path: README.svg

      - name: Commit changes
        run: |
          git config --global user.name 'Zagham Nadeem'
          git config --global user.email 'bit.bytes@outlook.com'
          git add README.svg
          git commit -m "Update snake animation"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
